language: python
python:
  - "3.6"

# command to install dependencies
before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="inventarium.settings.travis"

# command to run tests
script:
  - python manage.py test
  